# Generated by Django 5.0.1 on 2024-01-23 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('car_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image_car', models.FileField(blank=True, null=True, upload_to='images/')),
                ('brand_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.brand')),
            ],
        ),
    ]
